### PR TITLE
Refactor of test functions in the Factory Test Code

### PR DESCRIPTION
**Pull request by NULLbodyHERE**
Hello,

This PR pertains to issue #91. I have attempted to refactor all test functions in the GPAD_Factory_Test program. By doing so, I thought it would be appropriate to modify the version to 1.30. Firstly, I'll present a brief overview to the impact of my modifications and then break down the design.

#### Positives
- All peripherals can now be tested in some capacity after initialisation.
- Added functionality to mute button via DailyStruggleButton (DSB) debouncing library.
- All test actions are printed to the serial monitor to affirm functionality.
 
#### Negatives
- 92% of the dynamic memory capacity has been filled which means limited further expansion of tests. However, tests are fairly comprehensive as it stands.
- DSB library works via polling and not via interrupts. Especially during CPU-intensive tasks, such as testing the LCD, the mute button is not as responsive as it could be (at least, in the Wokwi simulation).

# Design
Functionality testing has been organised into _test groups_, where each group is comprised of individual tests. The groups and their respective tests are as follows:

### 1. Mute Button
Before any other tests are conducted, it is appropriate and necessary that the functionality of the mute button is verified. This is because each button action enables the tester to control their position in the test program. After initialisation, the serial monitor will display the actions of the button in real-time. The actions are:

**Single press:**  this skips to the next test within the current test group.

**Long press:** this enables automatic toggling of tests within the current test group. Currently, it is activated by pressing the button for 1000ms. Toggle the auto feature off by repeating the long press.

**Multi press:** this skips to the next test group. Currently, it is activated by a double press within 400ms.

_Note - although the DSB library provides it, the option to 'hold' press has not been enabled._

### 2. LEDs
This category consists of internal (built-in) and external (lights) LEDs. I attempted to match @ForrestErickson's description of the requirements.

**Built-in LED:** it is set to 'wink' when tested.

**Lights:**
1. Sequential lighting of LEDs individually.
2. Sequential lighting of all LEDs but one.
3. Lighting all LEDs.

### 3. Buzzer
Given that one frequency has been selected for testing, the buzzer is currently tested in both a continuous and an intermittent fashion. The serial monitor makes it clear as to which tone frequency and which intermittent pulse frequency is being generated.

### 4. I2C Scan
A full scan is triggered by a single press. Within the code, it is necessary to specify the target (or expected) primary address and the target number of I2C devices to be found. The serial monitor will notify the tester of whether the target address and target number of devices were found. An alert will be printed if the target address was not found, but error messages will print if the number of devices deviated from the target. The error message will include the number of addresses returning a particular error.

### 5. LCD
Although efforts have been made to optimise the code (without removing abstraction layers), this test group is particularly CPU intensive, which results in occasional omissions of mute button actions (at least, in the Wokwi simulator). To mitigate this issue, it is best to press the mute button after all characters have been printed across the entire display. The characters are currently set to change every 1000ms. The tests are as follows:

1. Backlight test.
2. Dead pixels test (by filling whole display).
3. Testing individual grid coordinates against a filled background.
4. Testing individual grid coordinates against a clear background.
5. Testing of all ASCII characters across the whole display (ASCII 33->127).

### Final Note
As you know, the test functions all exist within the scope of the `loop()` function, which can cause some undesirable effects, if not careful. To avoid the endless repeating of serial monitor messages, and even some functions, I enclosed the functions within an if-loop that ran once despite being within the scope of `loop()`. This was due to the global variable `printStatus` being reset to _false_ only on the single press or multi-press action.
```
if (!printStatus) {    // print once
  Serial.println("Now winking built-in LED.");   
  printStatus = true;
}
```

Big thanks to @ForrestErickson for providing comprehensive detail of this issue. Thank you @RobertLRead for opening this issue up to newcomers like myself! Please, don't hesitate to critique my work. I am eager to learn!

Cheers!

NULLbodyHERE
[nullbody.h@gmail.com]

### CODE REVIEW

**Comment by ForrestErickson** [comment]
20221120 (Forrest) Lee has read the summary by @NULLbodyHERE to understand the changes. VERY NICE.
Next step will be to merge in the pull request and test the hardware with this new functionality.

CC: @RobertLRead

**Comment by ForrestErickson** [comment]
# Notes on test of V1.30 GPAD_Factory_Test.ino
Loaded into DUT SN: 2.  NOTE this DUT has the rework so that the USB to UART IC can reset the ATmega328 such as when the Serial Monitor connects in the Arduino IDE.
Tester: Forrest Lee Erickson
Date: 20221120

Compile with results:
> Sketch uses 11926 bytes (38%) of program storage space. Maximum is 30720 bytes.
Global variables use 1902 bytes (92%) of dynamic memory, leaving 146 bytes for local variables. Maximum is 2048 bytes.
Low memory available, stability problems may occur.

As noted by @NULLbodyHERE  the global memory is mostly consumed.

## Load Factory Test firmware in to DUT.
The DUT briefly displayed a message on the LCD (with back light) and then went blank. No Back light. Not Wink on built in.
Not sufficient time to read the display for full comprehension but I saw the version 1.3 part.

I opened the serial monitor and see the following message as the DUT starts up:

> image

**NOTE:** The ninth message from the start of reset on the serial monitor, "Found⸮"⸮٥⸮⸮⸮s). [TARGET NUMBER]" is new to Lee.

## Press Mute Button

1. Single short press and release.  
The DUT responded on the serial port with 
> 14:07:29.292 -> Switch pressed.
> 14:07:29.527 -> Switch released.  
 
No message on the LCD. No change on LIGHT0-4. No change on Builtin LED.

2. Single long (>1000 ms) press and release. 
The DUT responded on the serial port with 

> 14:10:18.390 -> Switch long-pressed.
> 14:10:18.390 -> -- Auto-toggle mode enabled. --

   No message on the LCD. No change on LIGHT0-4. No change on Builtin LED.

3. Long press (about 2000ms) and release. 
The DUT responded on the serial port with 

> 14:13:44.450 -> Switch pressed.
> 14:13:45.483 -> Switch long-pressed.
> 14:13:45.483 -> -- Auto-toggle mode disabled. --

 No message on the LCD. No change on LIGHT0-4. No change on Builtin LED.

## Auto-Toggle Mode Test
Pressed the mute button till the DUT displayed " -- Auto-toggle mode enabled. --"
Then did multi press.  Screen capture of result on Serial Monitor
> image
The DUT Lights were tested by a walking 1 and the walking zero. The BUILTIN LED was winked too. Then the test started over.  Lee did not hear an alarm.

Did quick press and the DUT went into the auto test for the buzzer. See screen shot.
> image
This test works.

Did another quick test and the DUT went into the auto test for Start I2C scan. See screen shot.
> image
This test works and reports the found address as expected.

With the test continuing, Lee then shorted the I2C data line (SDA) low. The I2C scan stopped and the DUT became unresponsive.
Lee reset the DUT and again put it in the I2C scan. Again shorted the data line low. Again the DUT became unresponsive.
> image

With the test continuing, Reset DUT. Put DUT into auto test for I2C.  Lee then shorted the I2C clock line (SCL) low. The I2C scan stopped and the DUT became unresponsive.
Lee reset the DUT and again put it in the I2C scan. Again shorted the clock line low. Again the DUT became unresponsive.
> image

When the DUT was unresponsive pressing the Mute button for a short press, Long Press or multi Press had no affect on the DUT.  Tried sending a "?" on the serial input and no response.


### This will need work. The expected result should be some report on the serial port that the I2C buss had an error and the DUT should continue to allow testing, 
There are two cases.
1. The I2C test continues reporting the result. When the short circuit on SDA is removed the test should again report the Target Primary address was found. 
2. The user quick presses the Mute button to move to other tests

**Comment by ForrestErickson** [comment]
# Resume testing Notes on test of V1.30 GPAD_Factory_Test.ino

## Testing of the "Now testing LCD functionality."
Lee watched the DUT and found he had to press the mute button to advance the tests. Oh of course it is not in the auto test mode.  This is as expected. 
Short presses advanced through the tests. The count through the individual characters is very tedious. Only rare instance would be of use.  Also in the case of characters other than alpha and digits the order of characters is not well known and so if there were an error the user would not likely notice it.  A test with all characters (or 80 characters) on one screen will be much more user friendly.

> image

Note the monitor occasional shows corrupt serial output.
> image
and
> 
image


### Test with non target I2C Device.
Connect an LCD with a different target address to the DUT at J105.
Reset the DUT.   Screen shot of serial monitor at reset.
> image
The test reports the target and the non target as expected. 

### Factory Test with the Manufacturing Unit Test, Maximum Current Tests
A review of the Manufacturing documentation at: https://github.com/PubInv/general-alarm-device/blob/main/Hardware/Documentation/ManufacturingUnitTestTroubleshooting.md  which relied on the behavior of the version 1.?02? test to light all LIGHTS and Buzzer for the maximum current test shows we cannot make this test with V1.3 So we should consider redesign of tests or adding another mode.  This version is incompatible with our manufacturing method.

## Conclusions or Using Version 1.30 

* Enables significantly more independent testing of the GPAD features.
* Enables significantly more detailed testing of the GPAD features.
* The factory test procedure and troubleshooting will need rewriting to reflect and take advantage of this changed and new functionality
* The user experience would be improved if the LCD gave status of the test where possible such as when changing test modes by when pressing the Mute button. It seams more natural to look at the LCD rather than the Serial Monitor .
* The Firmware should be improved to recover from I2C bus faults. Should report the nature of faults / unexpected tests.
* Found unexpected corruption of serial output.
* Conserve RAM space by storing text strings in program memory.   See: https://www.arduino.cc/reference/en/language/variables/utilities/progmem/
The syntax for "The F() macro" there like, "Serial.print(F("Write something on the Serial Monitor that is stored in FLASH"));"
* Feature request. Make compatible with ManufacturingUnitTestTroubleshooting.md  especially the maximum current test.

CC:
@NULLbodyHERE 
@RobertLRead 
@LokiMetaSmith

**Comment by ForrestErickson** [comment]
@NULLbodyHERE 
@LokiMetaSmith 
@RobertLRead 

#  Other.

The excellent write up of the Summary and  Design above should be incorporated into instructions for the use of this software probably in the ManufacturingUnitTestTroubleshooting.md  Or in a new reference and instruction document to which the ManufacturingUnitTestTroubleshooting.md would refer (link)

I would write up an issue now but I am a bit brain tired and want to think through the consequences of each path a bit. 

I think there are two principal activates.
1. Feature requests to the firm ware
2. Documentation updating or creating to reflect the firmware.

**Comment by NULLbodyHERE** [comment]
Hello @ForrestErickson,

I would like to discuss one of your improvement suggestions.

> The user experience would be improved if the LCD gave status of the test where possible such as when changing test modes by when pressing the Mute button. It seams more natural to look at the LCD rather than the Serial Monitor .

When it came to refactoring the test code, my design plan was such that the items being tested should wait in turn, as I presumed isolation of each peripheral would generate the best results. I also thought that I should avoid using the LCD in particular during testing other peripherals because should there be an issue with the LCD, the user would no longer be able to gain feedback of which mode they are in. However, one could double up the serial monitor with the LCD. 

Further, when it comes to testing the LCD in particular, there will be a need to crosscheck the information displayed on the screen with what the microcontroller is actually driving to the display. So, I thought it would be more intuitive to consistently use the serial monitor to display expected behaviour rather than have the user switch between the two during the LCD tests.

Would you still recommend that I pursue this route? Thank you for your consideration.

NULLbodyHERE
[nullbody.h@gmail.com]

**Comment by ForrestErickson** [comment]
Regarding,

> I also thought that I should avoid using the LCD in particular during testing other peripherals because should there be an issue with the LCD, the user would no longer be able to gain feedback of which mode they are in. However, one could double up the serial monitor with the LCD.

I am pondering what you wrote to consider any down side of writing to the LCD.  So long as a failed write to the LCD  does not block code execution writing to the LCD seams a plus.  Which reminds me. The wire library allows a time out to be set which I am guessing would allow for code to give up on an I2C transmission which is not acknowledges with in the time out.  This would be good to understand and use to improve diagnostics.

So, regarding  "Would you still recommend that I pursue this route?" I think yes.

Try some experiments to see if you can find a down side which I have not anticipated.

**Pull request merged**
